In [2]:
import pandas as pd
import re

df_root = pd.read_csv('C:/Users/lui-m/Documents/GitHub/DS_Notebooks/ComunidadeDS/FTC_Python/datasets/train.csv')
df_root.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [5]:
# Fazendo cópia do dataframe lido
df = df_root.copy()

# Removendo espaço da string
for i in range(len(df)):
    df.loc[i, 'ID'] = df.loc[i, 'ID'].strip()
    df.loc[i, 'Delivery_person_ID'] = df.loc[i, 'Delivery_person_ID'].strip()
    
# Excluindo as linhas com a idade dos entregadores vazia
linhas_nao_vazias = df['Delivery_person_Age'] != 'NaN '
df = df.loc[linhas_nao_vazias, :]

# Conversao de texto/categoria/string para numeros inteiros
df['Delivery_person_Age'] = df['Delivery_person_Age'].astype(int)

# Conversao de texto/categoria/string para numeros decimais
df['Delivery_person_Ratings'] = df['Delivery_person_Ratings'].astype(float)

# Conversao de texto para data
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='%d-%m-%Y')

# Remove as linhas da coluna multiple_deliveries que tenham o conteúdo igual a 'NqN ' e fazendo o cast para inteiro
linhas_nao_vazias = df['multiple_deliveries'] != 'NaN '
df = df.loc[linhas_nao_vazias, :]
df['multiple_deliveries'] = df['multiple_deliveries'].astype(int)

# Removendo texto de números e resetando index
df = df.reset_index(drop=True)
for i in range(len(df)):
    df.loc[i, 'Time_taken(min)'] = re.findall(r'\d+', df.loc[i, 'Time_taken(min)'])

In [8]:
# 1. Qual o número total de entregas cadastradas na base de dados?
total_entregas = df.shape[0]
print(f'O número total de entregas cadastradas é: {total_entregas}')

O número total de entregas cadastradas é: 42805

In [12]:
# 2. Qual o número total de entregadores únicos cadastrados na base de dados?
entregadores_unicos = df['Delivery_person_ID'].unique()
print(f'O número total de entregadores únicos cadastrados na base de dados é de: {len(entregadores_unicos)}')

O número total de entregadores únicos cadastrados na base de dados é de: 1320

In [13]:
# 3. Qual a idade do entregador mais velho? E do mais novo?
maior_idade = df['Delivery_person_Age'].max()
menor_idade = df['Delivery_person_Age'].min()

print(f'O entregador mais velho tem {maior_idade} anos')
print(f'O entregador mais novo tem {menor_idade} anos')

O entregador mais velho tem 50 anos
O entregador mais novo tem 15 anos

In [22]:
# 3. Qual a idade do entregador mais velho? E do mais novo?
idades_ordenadas = df['Delivery_person_Age'].sort_values(ascending=False)
idades_ordenadas[30363]

50

In [25]:
# Também podemos utilizar a função sort_values no próprio dataframe, fazendo o corte por coluna
df.sort_values('Delivery_person_Age', ascending=False)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
30363,0xbf33,KNPRES03DEL03,50,6.0,-26.469003,-80.316344,26.559003,80.406344,2022-02-14,NaN,22:55:00,conditions NaN,NaN,3,Drinks,scooter,0,No,NaN,[17]
27254,0x404,CHENRES04DEL01,50,6.0,-13.029780,-80.208812,13.099780,80.278812,2022-03-18,NaN,23:55:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Metropolitian,[20]
35712,0x466,CHENRES14DEL02,50,6.0,13.026279,80.174568,13.106279,80.254568,2022-03-20,NaN,23:10:00,conditions NaN,NaN,3,Meal,scooter,0,No,Metropolitian,[14]
26636,0x3fd,BANGRES13DEL01,50,6.0,-12.935662,-77.614130,13.045662,77.724130,2022-03-06,NaN,17:30:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Metropolitian,[28]
9486,0x5b0,MYSRES04DEL01,50,6.0,12.308500,76.665808,12.418500,76.775808,2022-03-18,NaN,20:10:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Metropolitian,[35]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22286,0x3f7,CHENRES04DEL01,15,1.0,-13.029780,-80.208812,13.139780,80.318812,2022-03-31,NaN,22:40:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Urban,[15]
22268,0x1ea0,BANGRES17DEL02,15,1.0,12.972532,77.608179,13.022532,77.658179,2022-03-21,NaN,17:40:00,conditions NaN,NaN,3,Drinks,bicycle,1,No,Metropolitian,[23]
21004,0x3ed,RANCHIRES09DEL01,15,1.0,-23.351058,-85.325731,23.421058,85.395731,2022-03-27,NaN,21:35:00,conditions NaN,NaN,3,Buffet,electric_scooter,2,Yes,Metropolitian,[44]
25517,0x3f2,BANGRES02DEL02,15,1.0,12.970221,77.645396,13.050221,77.725396,2022-03-02,NaN,21:45:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Urban,[20]
31177,0x622,CHENRES03DEL02,15,1.0,-13.091809,80.219104,13.111809,80.239104,2022-03-03,NaN,11:50:00,conditions NaN,NaN,3,Buffet,scooter,0,No,Metropolitian,[33]

In [29]:
# 4. Qual o ID do entregador com a maior idade? E o ID do entregaor com a menor idade?
df_maior_idade = df.loc[df['Delivery_person_Age'] == maior_idade]
df_maior_idade

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
3357,0x46d,BANGRES05DEL01,50,6.0,-12.970324,-77.645748,13.010324,77.685748,2022-03-13,NaN,12:30:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Urban,[25]
4405,0x493,HYDRES17DEL01,50,6.0,-17.451976,-78.385883,17.561976,78.495883,2022-04-04,NaN,23:20:00,conditions NaN,NaN,3,Snack,bicycle,0,No,Metropolitian,[27]
4842,0x4f2,JAPRES08DEL01,50,6.0,-26.910262,-75.783013,27.020262,75.893013,2022-03-18,NaN,18:50:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,[20]
5021,0x430,BANGRES19DEL01,50,6.0,12.914264,77.678400,13.024264,77.788400,2022-04-06,NaN,20:55:00,conditions NaN,NaN,3,Meal,electric_scooter,1,No,Metropolitian,[18]
5293,0xbef1,AGRRES13DEL02,50,6.0,-27.159795,-78.042990,27.209795,78.092990,2022-02-13,NaN,18:05:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,[20]
5994,0x427,JAPRES06DEL02,50,6.0,26.911927,75.797282,27.041927,75.927282,2022-04-02,NaN,22:10:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Urban,[20]
6590,0x3eb,MYSRES15DEL02,50,6.0,-12.352058,-76.606650,12.372058,76.626650,2022-03-15,NaN,10:00:00,conditions NaN,NaN,3,Buffet,scooter,1,No,Metropolitian,[14]
7204,0xd42,VADRES09DEL01,50,6.0,0.000000,0.000000,0.010000,0.010000,2022-03-21,NaN,08:35:00,conditions NaN,NaN,3,Meal,bicycle,1,No,Metropolitian,[22]
8918,0x3f0,BANGRES010DEL01,50,6.0,12.933298,77.614293,13.003298,77.684293,2022-03-12,NaN,18:25:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Urban,[17]
8952,0x3ef,RANCHIRES13DEL01,50,6.0,-23.374989,-85.335486,23.444989,85.405486,2022-03-20,NaN,17:55:00,conditions NaN,NaN,3,Snack,bicycle,1,No,Metropolitian,[32]
9486,0x5b0,MYSRES04DEL01,50,6.0,12.308500,76.665808,12.418500,76.775808,2022-03-18,NaN,20:10:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Metropolitian,[35]
10085,0xbffc,DEHRES18DEL02,50,6.0,0.000000,0.000000,0.020000,0.020000,2022-02-13,NaN,08:50:00,conditions NaN,NaN,3,Snack,scooter,0,No,Metropolitian,[25]
11555,0x940,SURRES02DEL02,50,6.0,21.186608,72.794136,21.206608,72.814136,2022-03-01,NaN,11:25:00,conditions NaN,NaN,3,Meal,scooter,1,No,Urban,[22]
12452,0x490,COIMBRES03DEL02,50,6.0,11.025083,77.015393,11.105083,77.095393,2022-03-23,NaN,20:50:00,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Urban,[11]
12826,0x434,RANCHIRES01DEL02,50,6.0,-23.416792,-85.316842,23.466792,85.366842,2022-03-13,NaN,20:40:00,conditions NaN,NaN,3,Buffet,motorcycle,0,No,Metropolitian,[28]
13257,0x3f6,MYSRES06DEL02,50,6.0,12.323994,76.626167,12.373994,76.676167,2022-03-03,NaN,21:25:00,conditions NaN,NaN,3,Meal,scooter,0,No,Urban,[15]
14021,0x421,CHENRES19DEL01,50,6.0,12.986047,80.218114,12.996047,80.228114,2022-03-17,NaN,09:35:00,conditions NaN,NaN,3,Drinks,bicycle,0,No,Metropolitian,[12]
14055,0x43c,HYDRES14DEL01,50,6.0,17.426228,78.407495,17.536228,78.517495,2022-04-02,NaN,22:50:00,conditions NaN,NaN,3,Meal,motorcycle,1,No,Urban,[19]
15806,0x3fa,RANCHIRES06DEL02,50,6.0,23.357804,85.325146,23.377804,85.345146,2022-03-13,NaN,09:05:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,[22]
16134,0x400,COIMBRES07DEL01,50,6.0,10.961850,76.971082,10.971850,76.981082,2022-03-05,NaN,09:15:00,conditions NaN,NaN,3,Snack,electric_scooter,0,No,Urban,[14]
16668,0x412,CHENRES010DEL01,50,6.0,-13.066762,-80.251865,13.076762,80.261865,2022-03-17,NaN,09:15:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian,[20]
17868,0xc363,BHPRES08DEL03,50,6.0,23.232537,77.429845,23.322537,77.519845,2022-02-18,NaN,21:25:00,conditions NaN,NaN,3,Buffet,scooter,1,No,Metropolitian,[17]
18245,0x3fb,INDORES02DEL03,50,6.0,-22.651847,-75.881991,22.711847,75.941991,2022-03-05,NaN,19:30:00,conditions NaN,NaN,3,Drinks,bicycle,0,No,Metropolitian,[30]
19081,0xd0bc,ALHRES01DEL02,50,6.0,25.454648,81.834502,25.504648,81.884502,2022-02-15,NaN,21:55:00,conditions NaN,NaN,3,Snack,motorcycle,1,No,Urban,[33]
20079,0x810,HYDRES06DEL01,50,6.0,17.455894,78.375467,17.525894,78.445467,2022-04-06,NaN,17:30:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian,[35]
21121,0xc7d6,ALHRES08DEL03,50,6.0,25.450329,81.834279,25.590329,81.974279,2022-02-16,NaN,17:45:00,conditions NaN,NaN,3,Drinks,scooter,0,No,Metropolitian,[29]
22017,0x1060,BANGRES05DEL03,50,6.0,12.970324,77.645748,13.030324,77.705748,2022-03-09,NaN,22:15:00,conditions NaN,NaN,3,Buffet,electric_scooter,0,No,Urban,[19]
22822,0x420,SURRES13DEL01,50,6.0,-21.170096,-72.789122,21.180096,72.799122,2022-03-15,NaN,10:10:00,conditions NaN,NaN,3,Meal,motorcycle,0,No,Metropolitian,[17]
23464,0xbf34,KNPRES16DEL02,50,6.0,26.482581,80.315628,26.612581,80.445628,2022-02-12,NaN,18:30:00,conditions NaN,NaN,3,Buffet,scooter,1,No,Metropolitian,[41]
23812,0x40c,COIMBRES08DEL03,50,6.0,11.001852,76.976268,11.061852,77.036268,2022-03-01,NaN,17:50:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Metropolitian,[16]
24525,0x694,RANCHIRES09DEL02,50,6.0,23.351058,85.325731,23.371058,85.345731,2022-03-21,NaN,08:40:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Metropolitian,[20]
25607,0x3f4,COIMBRES20DEL02,50,6.0,-10.994136,-76.963303,11.074136,77.043303,2022-03-06,NaN,17:20:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,NaN,[17]
25776,0x3ea,MUMRES20DEL03,50,6.0,19.103249,72.846749,19.133249,72.876749,2022-03-24,NaN,23:20:00,conditions NaN,NaN,3,Meal,electric_scooter,1,No,Metropolitian,[18]
26636,0x3fd,BANGRES13DEL01,50,6.0,-12.935662,-77.614130,13.045662,77.724130,2022-03-06,NaN,17:30:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Metropolitian,[28]
27254,0x404,CHENRES04DEL01,50,6.0,-13.029780,-80.208812,13.099780,80.278812,2022-03-18,NaN,23:55:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Metropolitian,[20]
27769,0x480,BANGRES15DEL01,50,6.0,-12.975377,-77.696664,13.015377,77.736664,2022-03-01,NaN,13:55:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian,[15]
28736,0xbf12,BHPRES20DEL03,50,6.0,23.235123,77.398886,23.325123,77.488886,2022-02-16,NaN,23:10:00,conditions NaN,NaN,3,Snack,bicycle,2,No,Metropolitian,[39]
29072,0x4cc,MUMRES20DEL01,50,6.0,-19.103249,-72.846749,19.213249,72.956749,2022-03-16,NaN,22:00:00,conditions NaN,NaN,3,Meal,scooter,1,No,Urban,[30]
29346,0x706,VADRES09DEL02,50,6.0,0.000000,0.000000,0.050000,0.050000,2022-03-11,NaN,22:30:00,conditions NaN,NaN,3,Drinks,scooter,0,No,Metropolitian,[28]
30363,0xbf33,KNPRES03DEL03,50,6.0,-26.469003,-80.316344,26.559003,80.406344,2022-02-14,NaN,22:55:00,conditions NaN,NaN,3,Drinks,scooter,0,No,NaN,[17]
31491,0xbf01,KOLRES06DEL02,50,6.0,-22.533662,-88.366217,22.663662,88.496217,2022-02-18,NaN,21:50:00,conditions NaN,NaN,3,Snack,scooter,1,No,Metropolitian,[28]
32582,0xbf76,AGRRES20DEL03,50,6.0,-27.158822,-78.045359,27.248822,78.135359,2022-02-14,NaN,23:55:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Urban,[16]
35699,0xbef2,DEHRES13DEL01,50,6.0,30.366322,78.070453,30.436322,78.140453,2022-02-14,NaN,18:05:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Metropolitian,[25]
35712,0x466,CHENRES14DEL02,50,6.0,13.026279,80.174568,13.106279,80.254568,2022-03-20,NaN,23:10:00,conditions NaN,NaN,3,Meal,scooter,0,No,Metropolitian,[14]
36215,0x3f1,VADRES09DEL03,50,6.0,0.000000,0.000000,0.090000,0.090000,2022-04-06,NaN,19:20:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Metropolitian,[36]
36296,0x5e0,MUMRES07DEL03,50,6.0,-19.091458,72.827808,19.121458,72.857808,2022-03-11,NaN,21:50:00,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Urban,[26]
37270,0xa24,RANCHIRES14DEL03,50,6.0,0.000000,0.000000,0.030000,0.030000,2022-03-21,NaN,21:10:00,conditions NaN,NaN,3,Buffet,bicycle,1,No,Metropolitian,[39]
37765,0x3e9,MYSRES04DEL03,50,6.0,-12.308500,-76.665808,12.398500,76.755808,2022-03-12,NaN,17:45:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian,[40]
38586,0x4e4,VADRES17DEL01,50,6.0,0.000000,0.000000,0.110000,0.110000,2022-03-20,NaN,21:55:00,conditions NaN,NaN,3,Meal,scooter,1,Yes,Metropolitian,[48]
39389,0xbef4,KNPRES19DEL03,50,6.0,-26.490950,-80.318656,26.520950,80.348656,2022-02-13,NaN,00:00:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,[15]
39489,0x5fc,INDORES11DEL03,50,6.0,22.751234,75.889490,22.781234,75.919490,2022-03-17,NaN,20:40:00,conditions NaN,NaN,3,Buffet,scooter,0,No,Metropolitian,[28]
40202,0x53e,BANGRES12DEL01,50,6.0,-12.939496,77.625999,12.949496,77.635999,2022-03-19,NaN,09:40:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian,[19]
42556,0x2950,VADRES04DEL02,50,6.0,0.000000,0.000000,0.020000,0.020000,2022-03-19,NaN,10:40:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Urban,[28]

In [30]:
df_menor_idade = df.loc[df['Delivery_person_Age'] == menor_idade]
df_menor_idade

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
2236,0x564,JAPRES15DEL03,15,1.0,-26.891191,75.802083,26.981191,75.892083,2022-03-12,NaN,17:20:00,conditions NaN,NaN,3,Meal,motorcycle,0,No,Urban,[15]
2717,0xcd0,INDORES010DEL03,15,1.0,22.750040,75.902847,22.810040,75.962847,2022-04-03,NaN,20:30:00,conditions NaN,NaN,3,Snack,scooter,1,No,Metropolitian,[29]
2761,0x91a,SURRES17DEL03,15,1.0,21.149569,72.772697,21.209569,72.832697,2022-03-21,NaN,22:10:00,conditions NaN,NaN,3,Buffet,bicycle,1,No,Metropolitian,[20]
5531,0x474,CHENRES15DEL03,15,1.0,13.026286,80.275235,13.056286,80.305235,2022-03-11,NaN,20:50:00,conditions NaN,NaN,3,Drinks,bicycle,1,No,Metropolitian,[25]
8595,0x73f,BANGRES05DEL01,15,1.0,12.970324,77.645748,13.080324,77.755748,2022-03-25,NaN,23:25:00,conditions NaN,NaN,3,Buffet,motorcycle,2,No,Metropolitian,[34]
10241,0x1b49,MUMRES14DEL02,15,1.0,19.181300,72.836191,19.231300,72.886191,2022-03-30,NaN,20:55:00,conditions NaN,NaN,3,Buffet,motorcycle,1,No,Metropolitian,[39]
10457,0x40b,SURRES12DEL01,15,1.0,-21.183434,-72.814492,21.193434,72.824492,2022-03-05,NaN,11:30:00,conditions NaN,NaN,3,Meal,scooter,1,No,Urban,[27]
11361,0x523,INDORES03DEL02,15,1.0,22.751857,75.866699,22.801857,75.916699,2022-03-24,NaN,21:15:00,conditions NaN,NaN,3,Buffet,bicycle,0,No,Metropolitian,[28]
14224,0x18b0,RANCHIRES02DEL01,15,1.0,0.000000,0.000000,0.070000,0.070000,2022-03-16,NaN,23:55:00,conditions NaN,NaN,3,Meal,bicycle,1,No,Metropolitian,[21]
14981,0x550,CHENRES08DEL02,15,1.0,13.022394,80.242439,13.072394,80.292439,2022-03-11,NaN,18:10:00,conditions NaN,NaN,3,Snack,bicycle,0,No,Metropolitian,[17]
15130,0x58c,MUMRES02DEL01,15,1.0,-19.221315,72.862381,19.231315,72.872381,2022-03-30,NaN,12:05:00,conditions NaN,NaN,3,Snack,scooter,0,No,Metropolitian,[23]
15488,0xe4c,MYSRES05DEL03,15,1.0,12.323978,76.627961,12.413978,76.717961,2022-03-27,NaN,20:00:00,conditions NaN,NaN,3,Meal,electric_scooter,0,No,Urban,[24]
19987,0x3fc,BANGRES16DEL02,15,1.0,13.029198,77.570997,13.159198,77.700997,2022-03-06,NaN,17:15:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Metropolitian,[28]
21004,0x3ed,RANCHIRES09DEL01,15,1.0,-23.351058,-85.325731,23.421058,85.395731,2022-03-27,NaN,21:35:00,conditions NaN,NaN,3,Buffet,electric_scooter,2,Yes,Metropolitian,[44]
21701,0x415,VADRES17DEL01,15,1.0,0.000000,0.000000,0.070000,0.070000,2022-03-29,NaN,00:00:00,conditions NaN,NaN,3,Snack,scooter,0,No,Urban,[27]
22122,0x616c,SURRES07DEL02,15,1.0,21.170798,72.790489,21.220798,72.840489,2022-03-24,NaN,17:30:00,conditions NaN,NaN,3,Snack,scooter,1,No,Metropolitian,[32]
22268,0x1ea0,BANGRES17DEL02,15,1.0,12.972532,77.608179,13.022532,77.658179,2022-03-21,NaN,17:40:00,conditions NaN,NaN,3,Drinks,bicycle,1,No,Metropolitian,[23]
22286,0x3f7,CHENRES04DEL01,15,1.0,-13.029780,-80.208812,13.139780,80.318812,2022-03-31,NaN,22:40:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Urban,[15]
24360,0xbb3,CHENRES15DEL03,15,1.0,13.026286,80.275235,13.116286,80.365235,2022-03-20,NaN,22:50:00,conditions NaN,NaN,3,Drinks,scooter,0,No,Metropolitian,[27]
25070,0x730,INDORES15DEL02,15,1.0,22.760072,75.892574,22.840072,75.972574,2022-03-12,NaN,17:35:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Metropolitian,[27]
25332,0x6e0,CHENRES06DEL03,15,1.0,13.054347,80.257221,13.114347,80.317221,2022-03-01,NaN,18:20:00,conditions NaN,NaN,3,Meal,electric_scooter,1,No,Urban,[21]
25517,0x3f2,BANGRES02DEL02,15,1.0,12.970221,77.645396,13.050221,77.725396,2022-03-02,NaN,21:45:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Urban,[20]
26283,0x681,CHENRES07DEL03,15,1.0,13.081878,80.248519,13.111878,80.278519,2022-04-03,NaN,21:50:00,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Metropolitian,[27]
26339,0x406,PUNERES14DEL01,15,1.0,18.516216,73.842527,18.586216,73.912527,2022-03-27,NaN,19:30:00,conditions NaN,NaN,3,Buffet,scooter,1,No,Metropolitian,[38]
27885,0x137e,MYSRES19DEL02,15,1.0,12.334022,76.618203,12.354022,76.638203,2022-03-01,NaN,09:35:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian,[13]
29330,0x32aa,JAPRES11DEL01,15,1.0,26.902940,75.793007,26.912940,75.803007,2022-03-09,NaN,10:05:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Urban,[19]
30024,0x4240,PUNERES05DEL02,15,1.0,18.543626,73.905101,18.623626,73.985101,2022-03-08,NaN,21:25:00,conditions NaN,NaN,3,Meal,bicycle,0,No,Metropolitian,[21]
31177,0x622,CHENRES03DEL02,15,1.0,-13.091809,80.219104,13.111809,80.239104,2022-03-03,NaN,11:50:00,conditions NaN,NaN,3,Buffet,scooter,0,No,Metropolitian,[33]
32834,0x85c,COIMBRES17DEL02,15,1.0,11.026117,76.944652,11.046117,76.964652,2022-03-09,NaN,09:10:00,conditions NaN,NaN,3,Snack,scooter,1,No,Metropolitian,[19]
33828,0xdc0,COIMBRES03DEL03,15,1.0,11.025083,77.015393,11.085083,77.075393,2022-03-03,NaN,18:55:00,conditions NaN,NaN,3,Meal,motorcycle,1,No,Metropolitian,[28]
34851,0x451,HYDRES14DEL03,15,1.0,-17.426228,-78.407495,17.486228,78.467495,2022-03-19,NaN,19:05:00,conditions NaN,NaN,3,Buffet,electric_scooter,1,No,Urban,[30]
35392,0x424,PUNERES20DEL02,15,1.0,-18.592718,-73.773572,18.672718,73.853572,2022-03-16,NaN,20:25:00,conditions NaN,NaN,3,Buffet,scooter,1,No,Urban,[30]
36693,0x4a6,COIMBRES07DEL02,15,1.0,-10.961850,-76.971082,11.091850,77.101082,2022-03-02,NaN,19:55:00,conditions NaN,NaN,3,Drinks,electric_scooter,0,No,Metropolitian,[24]
36699,0x1144,MYSRES05DEL01,15,1.0,12.323978,76.627961,12.433978,76.737961,2022-03-29,NaN,22:10:00,conditions NaN,NaN,3,Snack,electric_scooter,0,No,Metropolitian,[30]
37825,0x442,CHENRES16DEL02,15,1.0,-13.049645,-80.242268,13.129645,80.322268,2022-03-08,NaN,23:05:00,conditions NaN,NaN,3,Snack,bicycle,0,No,Metropolitian,[25]
38717,0x49c,COIMBRES14DEL02,15,1.0,11.003681,76.975525,11.133681,77.105525,2022-04-02,NaN,23:45:00,conditions NaN,NaN,3,Meal,scooter,0,No,Metropolitian,[25]
41688,0x2314,VADRES04DEL01,15,1.0,0.000000,0.000000,0.070000,0.070000,2022-03-14,NaN,17:40:00,conditions NaN,NaN,3,Drinks,scooter,0,No,Metropolitian,[34]
42129,0x8d4,CHENRES02DEL02,15,1.0,13.086438,80.220672,13.216439,80.350672,2022-03-18,NaN,18:00:00,conditions NaN,NaN,3,Snack,electric_scooter,1,No,Urban,[26]

In [31]:
# 5. Quais os nomes das condições climáticas?
df['Weatherconditions'].unique()

array(['conditions Sunny', 'conditions Stormy', 'conditions Sandstorms',
       'conditions Cloudy', 'conditions Fog', 'conditions Windy',
       'conditions NaN'], dtype=object)

In [38]:
# 6. Quantas entregas foram realizadas sob condições climáticas de tempestade de areia? ( Sandstorms )
df_tempestade_areia = df.loc[df['Weatherconditions'] == 'conditions Sandstorms']
print(f'O número de entregas que foram realizadas sob a condição de tempestade de areia foi: {len(df_tempestade_areia)}')

O número de entregas que foram realizadas sob a condição de tempestade de areia foi: 7083

In [55]:
# 7. Quais eram as condicões climáticas da data mais recente de entrega?
df_entregas_recentes = df.sort_values('Order_Date', ascending=False) # Aqui eu tenho como retorno todo um dataframe
df_entregas_recentes.iloc[0, 11]

'conditions Windy'

In [58]:
# 8. Quantos tipos de densidade de trânsito existem na base de dados? Quais os nomes delas?
df['Road_traffic_density'].unique()

array(['High ', 'Jam ', 'Low ', 'Medium ', 'NaN '], dtype=object)

In [67]:
# 9. Quantos tipos de densidade de trânsito existem na base de dados? Quais os nomes delas?
condicoes_climaticas = list(df['Weatherconditions'].unique())

for condicao in condicoes_climaticas:
    numero_entregas = df.loc[df['Weatherconditions'] == condicao, :].shape[0]
    print(f'O numero de entregas feitas na densidade de transito {condicao} foi de {numero_entregas}')

O numero de entregas feitas na densidade de transito conditions Sunny foi de 6904
O numero de entregas feitas na densidade de transito conditions Stormy foi de 7226
O numero de entregas feitas na densidade de transito conditions Sandstorms foi de 7083
O numero de entregas feitas na densidade de transito conditions Cloudy foi de 7135
O numero de entregas feitas na densidade de transito conditions Fog foi de 7288
O numero de entregas feitas na densidade de transito conditions Windy foi de 7078
O numero de entregas feitas na densidade de transito conditions NaN foi de 91

In [72]:
# 10. Quantos entregadores únicos fizeram entregas em cada condição climática?
for condicao in condicoes_climaticas:
    entregadores_unicos_clima = df.loc[df['Weatherconditions'] == condicao, 'Delivery_person_ID'].nunique()
    print(f'{entregadores_unicos_clima} fizeram entregas na condicao climática {condicao}')

1233 fizeram entregas na condicao climática conditions Sunny
1234 fizeram entregas na condicao climática conditions Stormy
1239 fizeram entregas na condicao climática conditions Sandstorms
1246 fizeram entregas na condicao climática conditions Cloudy
1251 fizeram entregas na condicao climática conditions Fog
1230 fizeram entregas na condicao climática conditions Windy
87 fizeram entregas na condicao climática conditions NaN

In [78]:
#11. Quantas entregas foram feitas em cada tipo de densidade de trânsito?
densidades_transito = list(df['Road_traffic_density'].unique())
for densidade in densidades_transito:
    entregas_feitas = len(df.loc[df['Road_traffic_density'] == densidade])
    print(f'{entregas_feitas} foram feitas na densidade de trânsito {densidade}')

4212 foram feitas na densidade de trânsito High
13480 foram feitas na densidade de trânsito Jam
14605 foram feitas na densidade de trânsito Low
10417 foram feitas na densidade de trânsito Medium
91 foram feitas na densidade de trânsito NaN

In [80]:
#12. Quantos entregadores únicos fizeram entregas em cada tipo de densidade de trânsito?
for densidade in densidades_transito:
    entregadores_unicos = df.loc[df['Road_traffic_density'] == densidade, 'Delivery_person_ID'].nunique()
    print(f'{entregadores_unicos} entregadores únicos fizeram entregas no tipo de densidade {densidade}')

787 entregadores únicos fizeram entregas no tipo de densidade High
1306 entregadores únicos fizeram entregas no tipo de densidade Jam
1310 entregadores únicos fizeram entregas no tipo de densidade Low
1287 entregadores únicos fizeram entregas no tipo de densidade Medium
87 entregadores únicos fizeram entregas no tipo de densidade NaN

In [81]:
#13. Quantas cidades únicas existem na base? Quais são os seus nomes?
df['City'].unique()

array(['Urban ', 'Metropolitian ', 'Semi-Urban ', 'NaN '], dtype=object)

In [82]:
#14. Quantos tipos de veículos únicos existem na base?
df['Type_of_vehicle'].unique()

array(['motorcycle ', 'scooter ', 'electric_scooter ', 'bicycle '],
      dtype=object)

In [87]:
# 15. Qual o tipo de veículo que mais vez entregas com a condição de trânsito pesado? ( High )
tipos_veiculoss = list(df['Type_of_vehicle'].unique())

total_entregas = 0
tipo_veiculo = ''

for veiculo in tipos_veiculoss:
    filtro = (df['Type_of_vehicle'] == veiculo) & (df['Road_traffic_density'] == 'High')
    
    tipo_veiculo_entregas = df.loc[filtro, :].shape[0]
    
    print(f'{veiculo} -> {tipo_veiculo_entregas}')
    if total_entregas < tipo_veiculo_entregas:
        total_entregas = tipo_veiculo_entregas
        tipo_veiculo = veiculo
        
print(f'{tipo_veiculo} e {total_entregas}')

motorcycle  -> 0
scooter  -> 0
electric_scooter  -> 0
bicycle  -> 0
 e 0

In [88]:
velho = df.loc[ : , ['Delivery_person_Age']]
velho = velho.sort_values("Delivery_person_Age", ascending=False).iloc[0,0]

novo = df.loc[ : , ['Delivery_person_Age']] 
novo = novo.sort_values("Delivery_person_Age", ascending=True).iloc[0,0] 
print(f'\n3. Entregador mais velho:', velho, f'e entregador mais novo:', novo)

3. Entregador mais velho: 50 e entregador mais novo: 15